# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt --use-mirrors

before_script:
  - pip install -r test_requirements.txt --use-mirrors

script: 
  - py.test --pep8 mwtemplates -v --cov mwtemplates --doctest-modules tests/*_test.py

after_success:
  - coveralls
