# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.7"

# command to install dependencies, e.g. 
install: 
  - "pip install -r requirements.txt --use-mirrors"

#before_script:

# command to run tests, e.g. python setup.py test
script: nosetests
